spring:
  application:
    name: ff

  profiles:
    active: aaa , api

#tomcat



#
logging:
  level:
    com.example.ff: debug
    org.springframework: info

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8080
#
#langchain4j:
#  community:
#    chat-modle:
#      api-key :
#      model-name :

